=== open-contracting/standard/schema/meta-schema.json
{
  "id": "http://json-schema.org/draft-04/schema#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Core schema meta-schema",
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "positiveInteger": {
      "type": "integer",
      "minimum": 0
    },
    "positiveIntegerDefault0": {
      "allOf": [
        {
          "$ref": "#/definitions/positiveInteger"
        },
        {
          "default": 0
        }
      ]
    },
    "simpleTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "stringArray": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "default": {},
    "multipleOf": {
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": true
    },
    "maximum": {
      "type": "number"
    },
    "exclusiveMaximum": {
      "type": "boolean",
      "default": false
    },
    "minimum": {
      "type": "number"
    },
    "exclusiveMinimum": {
      "type": "boolean",
      "default": false
    },
    "maxLength": {
      "$ref": "#/definitions/positiveInteger"
    },
    "minLength": {
      "$ref": "#/definitions/positiveIntegerDefault0"
    },
    "pattern": {
      "type": "string",
      "format": "regex"
    },
    "additionalItems": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "$ref": "#"
        }
      ],
      "default": {}
    },
    "items": {
      "anyOf": [
        {
          "$ref": "#"
        },
        {
          "$ref": "#/definitions/schemaArray"
        }
      ],
      "default": {}
    },
    "maxItems": {
      "$ref": "#/definitions/positiveInteger"
    },
    "minItems": {
      "$ref": "#/definitions/positiveIntegerDefault0"
    },
    "uniqueItems": {
      "type": "boolean",
      "default": false
    },
    "maxProperties": {
      "$ref": "#/definitions/positiveInteger"
    },
    "minProperties": {
      "$ref": "#/definitions/positiveIntegerDefault0"
    },
    "required": {
      "$ref": "#/definitions/stringArray"
    },
    "additionalProperties": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "$ref": "#"
        }
      ],
      "default": {}
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "properties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "patternProperties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "anyOf": [
          {
            "$ref": "#"
          },
          {
            "$ref": "#/definitions/stringArray"
          }
        ]
      }
    },
    "enum": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "type": {
      "anyOf": [
        {
          "$ref": "#/definitions/simpleTypes"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/simpleTypes"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      ]
    },
    "format": {
      "type": "string"
    },
    "allOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "anyOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "oneOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "not": {
      "$ref": "#"
    },
    "$ref": {
      "title": "URI Reference",
      "description": "A reference to a statically identified schema.  This keyword must be set to an absolute URI or a relative reference as defined by [RFC 3986](https://www.rfc-editor.org/info/rfc3986), where its fragment (if any) can consist of a JSON Pointer as defined by [RFC 6901](https://datatracker.ietf.org/doc/html/rfc6901).",
      "type": "string"
    },
    "omitWhenMerged": {
      "title": "Omit when merged",
      "description": "Whether the field must be discarded during merging.",
      "type": "boolean",
      "default": false
    },
    "deprecated": {
      "title": "Deprecated",
      "description": "Information about the deprecation of this field.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "deprecatedVersion",
        "description"
      ],
      "properties": {
        "deprecatedVersion": {
          "title": "Deprecated version",
          "description": "The OCDS version in which this field was first deprecated.",
          "type": "string"
        },
        "description": {
          "title": "Description",
          "description": "A description of the reason for this field's deprecation.",
          "type": "string"
        }
      }
    },
    "codelist": {
      "title": "Codelist",
      "description": "The CSV file that defines the codes in the codelist that this field refers to.",
      "type": "string"
    },
    "openCodelist": {
      "title": "Open codelist",
      "description": "Whether the codelist that this field refers to is an open codelist.",
      "type": "boolean",
      "default": false
    },
    "wholeListMerge": {
      "title": "Whole list merge",
      "description": "Whether the field's value must be treated as a literal when merging.",
      "type": "boolean",
      "default": false
    }
  },
  "dependencies": {
    "exclusiveMaximum": [
      "maximum"
    ],
    "exclusiveMinimum": [
      "minimum"
    ]
  },
  "default": {},
  "additionalProperties": false
}

=== open-contracting/standard/schema/release-package-schema.json
{
  "id": "https://standard.open-contracting.org/schema/1__1__5/release-package-schema.json",
  "$schema": "https://standard.open-contracting.org/schema/1__2__0/meta-schema.json",
  "title": "Schema for an Open Contracting Release Package",
  "description": "The release package contains a list of releases along with some publishing metadata.",
  "type": "object",
  "required": [
    "releases",
    "version"
  ],
  "properties": {
    "uri": {
      "title": "Package identifier",
      "description": "The URI of this package that identifies it uniquely in the world. Recommended practice is to use a dereferenceable URI, where a persistent copy of this package is available.",
      "type": "string",
      "format": "uri",
      "deprecated": {
        "description": "This field was used by the `packages` field in the record package schema, which is deprecated.",
        "deprecatedVersion": "1.2"
      }
    },
    "version": {
      "title": "OCDS schema version",
      "description": "The version of the OCDS schema used in this package, expressed as major.minor For example: 1.0 or 1.1",
      "type": "string",
      "pattern": "^(\\d+\\.)(\\d+)$"
    },
    "extensions": {
      "title": "OCDS extensions",
      "description": "An array of OCDS extensions used in this package, in which each array item is the URL of an extension.json file.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "publishedDate": {
      "title": "Published date",
      "description": "The date that this package was published. If this package is generated 'on demand', this date should reflect the date of the last change to the underlying contents of the package.",
      "type": "string",
      "format": "date-time",
      "deprecated": {
        "description": "This field repeats the maximum `date` among the releases it contains.",
        "deprecatedVersion": "1.2"
      }
    },
    "releases": {
      "title": "Releases",
      "description": "An array of one or more OCDS releases.",
      "type": "array",
      "items": {
        "$ref": "https://standard.open-contracting.org/schema/1__1__5/release-schema.json"
      }
    },
    "publisher": {
      "title": "Publisher",
      "description": "Information to uniquely identify the publisher of this package.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the organization or department responsible for publishing this OCDS data.",
          "type": "string"
        },
        "scheme": {
          "title": "Scheme",
          "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
          "type": [
            "string",
            "null"
          ]
        },
        "uid": {
          "title": "uid",
          "description": "The unique ID for this entity under the given ID scheme.",
          "type": [
            "string",
            "null"
          ]
        },
        "uri": {
          "title": "URI",
          "description": "A URI to identify the publisher.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      },
      "deprecated": {
        "description": "This field is deprecated in favor of the `publisher` field in the release schema.",
        "deprecatedVersion": "1.2"
      }
    },
    "license": {
      "title": "License",
      "description": "A link to the license that applies to the data in this package. A Public Domain Dedication or [Open Definition Conformant](https://opendefinition.org/licenses/) license is recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions.",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the license URL as data. The page linking to the data can express the license.",
        "deprecatedVersion": "1.2"
      }
    },
    "publicationPolicy": {
      "title": "Publication policy",
      "description": "A link to a document describing the publishers [publication policy](https://standard.open-contracting.org/{{version}}/{{lang}}/guidance/publish/#finalize-your-publication-policy).",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the publication policy URL as data. The page linking to the data can express the publication policy.",
        "deprecatedVersion": "1.2"
      }
    }
  }
}

=== open-contracting/standard/schema/record-schema.json
{
  "id": "https://standard.open-contracting.org/schema/1__2__0/record-schema.json",
  "$schema": "https://standard.open-contracting.org/schema/1__2__0/meta-schema.json",
  "title": "Record",
  "description": "A record aggregates releases with the same open contracting process identifier (ocid). There should be a single record per ocid per [distribution](https://www.w3.org/TR/vocab-dcat-2/#Class:Distribution), where a distribution might be a specific API endpoint or a specific bulk download file.",
  "type": "object",
  "properties": {
    "ocid": {
      "title": "Open contracting process identifier",
      "description": "A globally unique identifier for the contracting process that the record describes. Alternatively, this identifier can refer to a planning process or a single stage of a multi-stage procedure. It is composed of an ocid prefix and an internal identifier. It is encouraged to separate the ocds prefix and the internal identifier with a hyphen (`-`). For more information, see the [identifiers](https://standard.open-contracting.org/{{version}}/{{lang}}/schema/identifiers/) reference.",
      "type": "string"
    },
    "releases": {
      "title": "Releases",
      "description": "All the releases about the contracting (or planning) process at the time of the record's publication. The releases must be sorted in date order, from oldest to newest.",
      "type": "array",
      "oneOf": [
        {
          "title": "Linked releases",
          "description": "A list of references to releases.",
          "items": {
            "$ref": "#/definitions/LinkedRelease"
          },
          "minItems": 1
        },
        {
          "title": "Embedded releases",
          "description": "A list of releases, with all the data.",
          "items": {
            "$ref": "https://standard.open-contracting.org/schema/1__1__5/release-schema.json"
          },
          "minItems": 1
        }
      ]
    },
    "compiledRelease": {
      "title": "Compiled release",
      "description": "The latest value of each field at the time of the record's publication. It follows the same schema as a release. A record should contain a compiled release.",
      "$ref": "https://standard.open-contracting.org/schema/1__1__5/release-schema.json"
    },
    "versionedRelease": {
      "title": "Versioned release",
      "description": "The history of values of each field up to the time of the record's publication.",
      "$ref": "https://standard.open-contracting.org/schema/1__1__5/versioned-release-validation-schema.json"
    }
  },
  "required": [
    "ocid"
  ],
  "definitions": {
    "LinkedRelease": {
      "title": "Linked release",
      "description": "A reference to a release.",
      "type": "object",
      "properties": {
        "url": {
          "title": "Release URL",
          "description": "The URL of the release which contains the URL of the package with the release `id` appended using a fragment identifier e.g. https://standard.open-contracting.org/{{version}}/{{lang}}/examples/tender.json#ocds-213czf-000-00001",
          "type": "string",
          "format": "uri"
        },
        "date": {
          "title": "Release Date",
          "description": "The date of the release. It should match the value of the `date` field of the release. This is used to sort the releases in the list in chronological order.",
          "type": "string",
          "format": "date-time"
        },
        "tag": {
          "title": "Release Tag",
          "description": "The tags of the release. It should match the value of the `tag` field of the release. This provides additional context when reviewing a record to see what types of releases are included for this ocid.",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "planning",
              "planningUpdate",
              "tender",
              "tenderAmendment",
              "tenderUpdate",
              "tenderCancellation",
              "award",
              "awardUpdate",
              "awardCancellation",
              "contract",
              "contractUpdate",
              "contractAmendment",
              "implementation",
              "implementationUpdate",
              "contractTermination",
              "compiled"
            ]
          },
          "codelist": "releaseTag.csv",
          "openCodelist": false,
          "minItems": 1
        }
      },
      "required": [
        "url",
        "date"
      ]
    }
  }
}

=== open-contracting/standard/schema/record-package-schema.json
{
  "id": "https://standard.open-contracting.org/schema/1__1__5/record-package-schema.json",
  "$schema": "https://standard.open-contracting.org/schema/1__2__0/meta-schema.json",
  "title": "Schema for an Open Contracting Record package",
  "description": "The record package contains a list of records along with some publishing metadata.",
  "type": "object",
  "properties": {
    "uri": {
      "title": "Package identifier",
      "description": "The URI of this package that identifies it uniquely in the world.",
      "type": "string",
      "format": "uri",
      "deprecated": {
        "description": "This field mirrored the `uri` field in the release package schema, which is deprecated.",
        "deprecatedVersion": "1.2"
      }
    },
    "version": {
      "title": "OCDS schema version",
      "description": "The version of the OCDS schema used in this package, expressed as major.minor For example: 1.0 or 1.1",
      "type": "string",
      "pattern": "^(\\d+\\.)(\\d+)$"
    },
    "extensions": {
      "title": "OCDS extensions",
      "description": "An array of OCDS extensions used in this package, in which each array item is the URL of an extension.json file.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "publisher": {
      "title": "Publisher",
      "description": "Information to uniquely identify the publisher of this package.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the organization or department responsible for publishing this OCDS data.",
          "type": "string"
        },
        "scheme": {
          "title": "Scheme",
          "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
          "type": [
            "string",
            "null"
          ]
        },
        "uid": {
          "title": "uid",
          "description": "The unique ID for this entity under the given ID scheme.",
          "type": [
            "string",
            "null"
          ]
        },
        "uri": {
          "title": "URI",
          "description": "A URI to identify the publisher.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      },
      "deprecated": {
        "description": "This field is deprecated in favor of the `publisher` field in the release schema.",
        "deprecatedVersion": "1.2"
      }
    },
    "license": {
      "title": "License",
      "description": "A link to the license that applies to the data in this package. A Public Domain Dedication or [Open Definition Conformant](https://opendefinition.org/licenses/) license is recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions.",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the license URL as data. The page linking to the data can express the license.",
        "deprecatedVersion": "1.2"
      }
    },
    "publicationPolicy": {
      "title": "Publication policy",
      "description": "A link to a document describing the publishers publication policy.",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the publication policy URL as data. The page linking to the data can express the publication policy.",
        "deprecatedVersion": "1.2"
      }
    },
    "publishedDate": {
      "title": "Published date",
      "description": "The date that this package was published. If this package is generated 'on demand', this date should reflect the date of the last change to the underlying contents of the package.",
      "type": "string",
      "format": "date-time",
      "deprecated": {
        "description": "This field repeats the maximum `date` among the releases it contains.",
        "deprecatedVersion": "1.2"
      }
    },
    "packages": {
      "title": "Packages",
      "description": "A list of URIs of all the release packages that were used to create this record package.",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "format": "uri"
      },
      "uniqueItems": true,
      "deprecated": {
        "description": "This field is deprecated, because it is rarely implemented, is rarely used, and depends on a publication pattern in which release packages are published at stable URLs.",
        "deprecatedVersion": "1.2"
      }
    },
    "records": {
      "title": "Records",
      "description": "The records for this data package.",
      "type": "array",
      "items": {
        "$ref": "https://standard.open-contracting.org/schema/1__2__0/record-schema.json"
      }
    }
  },
  "required": [
    "records",
    "version"
  ]
}
